### ISSUE TITLE
Crash on controller assignment

### ISSUE THREAD

**Issue by indirect** [jasarien/Provenance#120]
Steps:

1. Opened Settings
2. Tapped "Controller Settings"
3. Tapped "Player 1"

iPad Air, connected SNES30.

Symbolicated crash log: http://files.arko.net/3Q1k0n0p2B2b/Provenance%20%209-28-15,%208-07%20PM.crash

**Comment by jasarien** [comment]
I'll take a look later this evening. This UI is intended for selecting between multiple connected MFi controllers, not iCade controllers, but I agree it shouldn't crash at least.

**Comment by jasarien** [comment]
Should be fixed in latest commit.

However, as I said in my previous comment, this UI is for selecting between multiple connected MFi controllers and won't do anything for iCade controllers. If an iCade controller is detected, it will be setup as player 1, regardless of other controllers. Multiple iCade controllers might be implement in the future but I don't have any immediate plans to do so.
