### ISSUE TITLE
MFI Controllers and Apple TV

### ISSUE THREAD

**Issue by bytor99999** [jasarien/Provenance#128]
Sorry to open an issue for this. But is it possible to put in links in the readme.md file to MFI Controllers that will work with all the device types. I personally am using it with the new Apple TV, but I am sure others have the same type of question for iPhones/iPads etc. And I am sure you have tried with a few of these controllers. I don't even know if just plain bluetooth game controllers would work, or if it HAS to be MFI. And I have also heard that a couple of the MFI controllers are really bad.

You can even put in Amazon affiliate links to the controllers if you want. 

Thanks

Mark

**Comment by jasarien** [comment]
Provenance works with *all* MFi controllers and some iCade controllers. I don't know exactly which iCade controllers as I didn't write the feature (I'm pretty sure it works wth NES30 and SNES30). Other game controllers are not supported.

I can't speak for the quality of some MFi controllers. The ones I have used have all been varying quality, but what I'd call "good enough". Some are better than others, but none of them are "bad". With that said, in order to be certified MFi, the hardware has to pass Apple's quality control, so if Apple's happy enough to put their badge on it, that should be a seal of approval anyone can go by.

Since I haven't used all MFi controllers, I can't really recommend one in particular.

**Comment by bytor99999** [comment]
So far I just tried the SteelSeries Stratus and it doesn't ever show up under Bluetooth devices. Not that this is a emulator error. FYI.

**Comment by jasarien** [comment]
I have a Steelseries Stratus XL and it pairs with Apple TV, iOS and OS X just fine. Make sure you're performing the correct steps to pair it (follow the instructions from the manufacturer).

As you said, this isn't an issue with Provenance. I've confirmed myself that Provenance works with the Stratus XL.

**Comment by bytor99999** [comment]
Thanks. This one isn't the XL version, and yes, I tried performing the correct steps to pair it. ;) It is actually really easy on the device as when you first turn it on for the first time. But the Apple TV has the spinner going next to other devices and nothing ever shows up. Bummer. Guess I'll return this and try the XL version instead.

Thanks again for everything you have done here, we all really appreciate it.

**Comment by bytor99999** [comment]
My laptop finds it, but not my iPhone 6s Plus or the Apple TV 4. 

Again, I am just posting this in case someone later has the same type question and I can give them some information that might help them.

Mark

**Comment by jeremieweldin** [comment]
I just purchased a SteelSeries Stratus and it works great with my iPhone 6s Plus and Apple TV 4. Took a few min to show up on the Apple TV bluetooth section, but since it connected it has worked flawlessly.

**Comment by bytor99999** [comment]
Interesting. I let mine sit there for 30 minutes and it never showed up. I got the XL and it works flawlessly. But thanks for posting that you were able to get the Status to work.

Mark
