### ISSUE TITLE
Question about Unix-netplay.cpp

### ISSUE THREAD

**Issue by estherzinn** [jasarien/Provenance#150]
Hi! I'm new to developing and was looking through the code to understand more about how emulators work. I had a question about unix-netplay.cpp. I saw the following block and was wondering what this is used for, also what kind of passwords and usernames are being stored here, and where is this information sent?

```
	// get any required configuration variables
	int port, localPlayers;
	std::string server, username, password, key;
	g_config->getOption("SDL.NetworkIP", &server);
	g_config->getOption("SDL.NetworkUsername", &username);
	g_config->getOption("SDL.NetworkPassword", &password);
	g_config->getOption("SDL.NetworkGameKey", &key);
	g_config->getOption("SDL.NetworkPort", &port);
	g_config->getOption("SDL.NetworkPlayers", &localPlayers);
    
    
	g_config->setOption("SDL.NetworkIP", "");
	g_config->setOption("SDL.NetworkPassword", "");
	g_config->setOption("SDL.NetworkGameKey", "");

	}
```

**Comment by jasarien** [comment]
That's part of the FCEU emulator, which provides the NES support in Provenance. It's not actually used at all in Provenance, and isn't compiled into the app.

If it was implemented it would be used to connect to a server and enable NetPlay to emulate local multiplayer over the internet. The passwords and user names would be those set by the server host to limit who can connect.

Finally, since this code isn't actually used, there is no information to be sent, or stored.

**Comment by estherzinn** [comment]
Ok cool, that was what I figured, that it was part of a multiplayer feature that didn't make the final cut. Thank you! :)

**Comment by jasarien** [comment]
No worries. Feel free to ask any other questions you, might have. You can ask them here if you like, save creating extra issues.
