### ISSUE TITLE
non-MFI local multiplayer

### ISSUE THREAD

**Issue by peterlenagh** [jasarien/Provenance#154]
Is it possible to do 2 player / multiplayer with 8bitdo controllers? They can run in iCade mode, which is supported, but as I understand it iCade is pretty much a keyboard mapping so I don't think that would facilitate 2 player.

I assume when it says "Local multiplayer with external controllers" in the `README.md` it means via MFI controllers. Is it possible without MFI (using 8bitdos)?

Thanks for your help!

**Comment by jasarien** [comment]
I'm not 100% sure, since I didn't implement the iCade support. The way I understand it, iCade uses two keys per control (e.g., W is "press up" and E is "release up"). With the amount of controls, you'd pretty quickly run out of mappable keys (on an iOS keyboard at least) if you started connecting multiple controllers.

With that said, I don't even know if an iCade controller is capable of changing which keys is maps to its buttons. If not, then connecting two controllers would just press the same keys from each controller, which wouldn't work.

Your assumption is correct, local multiplayer in Provenance is via MFi controllers.

**Comment by peterlenagh** [comment]
@jasarien thanks for your reply.

@josejulio do you know if it would be possible? 8bitdo controllers support several other modes - [8Bitdo SFC30 modes](http://www.8bitdo.com/sfc30/manual.html).

...I'm looking at it and I'm thinking it's can't be done, seems like the other modes don't register button releases therefore couldn't work. Unless the iCade standard has a 2nd player mapping I don't know about (even then doesn't look like that's an existing "mode" on the 8bitdo controllers.)

thanks,
Pete

**Comment by josejulio** [comment]
@peterlenagh the only mode that is supported by an non-jailbreaked iOS is mode 3 (iCade). About multiplayer, as @jasarien says, the iCade needs 2 keys per button, an iCade is made of the dpad (4 buttons) and 8 buttons, a total of 24 keys. 

There is an implementation of the iCade format that supports two-player (http://gamedock.tv/ no longer for sale), they did by using lower and upper case keys (i.e. lower is player one, upper is player two), sadly, is not implement by 8bitdo (and not sure if they will, doesn't hurt to ask if the could). If they did, shouldn't be too hard to implement on Provenance.

I hope i've answered all your questions.

**Comment by jasarien** [comment]
Sounds like multiplayer for iCade depends on the hardware manufacturers supporting certain things, so I'm going to close this issue.

If the situation changes and 8Bitdo starts to support multiplayer, we can reopen this issue.
