### ISSUE TITLE
Latest Version compatible with iOS 7

### ISSUE THREAD

**Issue by tristan-k** [jasarien/Provenance#167]
Which is the latest version which is compatible with iOS 7?

**Comment by jasarien** [comment]
Provenance only runs on iOS 8 and above. The last iOS 7 version was well over a year a go and doesn't support many of the new features.

**Comment by tristan-k** [comment]
Alright thanks. I will have to stick to retroarch than.

**Comment by nraygun** [comment]
Is the older version that supports iOS 7 still available here somewhere? And if it is, would it compile and load using Xcode 8.2.1 to an iPhone 4?
I have this working on my iPhone 5s and it's awesome! Trying to do the same for my son who has an old iPhone 4 running iOS 7.1.2.

**Comment by nraygun** [comment]
I think I found a version that compiles and runs on the iPhone 4 running 7.1.2. It was version 1.1 but it seems to run really slow. I used Xcode 7.3.1 and had to disable "bitcode" (whatever that is).

Is there a better version out there for iOS 7?

**Comment by nraygun** [comment]
I was able to get version 1.03 compiled and running on my son's iPhone 4 running iOS 7. I had to disabled "bitcode", whatever that is, and use Xcode 7.3.1. So that's the good news.

The bad news is it runs really slow. Not really playable.

Is there a better version to use with iOS 7?

**Comment by jasarien** [comment]
If you made sure to build with the Release scheme (as opposed to debug), then the slowness is likely because its an iPhone 4. It's a device that is really showing its age these days and emulation isn't something it is very good at. Provenance was initially developed using an iPhone 5S, two generations ahead of an iPhone 4 and was only just able to emulate SNES and Genesis without hiccups in performance.

**Comment by nraygun** [comment]
Appreciate the response!
For some reason I was under the impression Provenance at one point ran on a 4.
Any suggestions for any emulation on an iPhone 4?
