### ISSUE TITLE
Steelseries Nimbus buttons aren't mapped properly in SNES games

### ISSUE THREAD

**Issue by whitverj** [jasarien/Provenance#181]
When I pair my Nimbus to my iPhone, it works well enough, except the X/Y A/B button mappings aren't quite right.  Is there an interface to remap physical buttons, or is that something that needs to be adjusted on a controller-by-controller basis?  

I don't have my controller in front of me, so I can't verify exactly what the issue is, but I'm wondering if it's because the nimbus has its X/Y and A/B positions reversed relative to where Nintendo put them on the SNES controller?

**Comment by jasarien** [comment]
The controllers are mapped so that the physical location of the buttons matches the layouts of the emulated controllers. The names of the buttons don't match. 

That is to say on SNES, the controller's A button maps to the SNES pad's B button because that's where the B button would have been. 

Other controllers follow the same method - the X button on the controller maps to the MegaDrive's A button etc.  

Button remapping has already been requested and will be implemented sometime in the future. #56

**Comment by whitverj** [comment]
I guess what I was saying was that, in my experience, the physical location of the button was NOT matching the layout of the emulated controller, at least with the Nimbus.

**Comment by jasarien** [comment]
Sure it does. The Nimbus A button is in the South position of the buttons were a compass. The button in the South position on the SNES controller is the B button. 

Therefore Provenance maps the Nimbus' A button to the SNES' B button. See the images:

![image](https://cloud.githubusercontent.com/assets/104444/11004407/f8363d6e-84af-11e5-9b65-dbb6f2920919.jpeg)
![image](https://cloud.githubusercontent.com/assets/104444/11004408/f86a5f04-84af-11e5-9df8-52e30a0d538e.jpeg)

**Comment by whitverj** [comment]
I know that's what's supposed to happen, but in my experience that's not what was going on.  I'll test again when time permits, and update as appropriate.

**Comment by whitverj** [comment]
I'm also on 1.2.1, and I see the current version is 1.2.3 - perhaps it's something that was addressed in a later release.

**Comment by jasarien** [comment]
That'll do it. 😂

Need to put a disclaimer before raising issues to make sure you're using the latest commit version, because even the tagged releases get out of date quickly.

**Comment by whitverj** [comment]
My bad!  It hadn't been that long ago since I built/installed the app, so I guess it didn't occur to me that there'd be a point update since then.  Ugh...I should know better, too...😳

**Comment by kudit** [comment]
Yay for visual aids!

**Comment by ianmc81** [comment]
Should this be working on the Apple TV build? I updated it today and my Nimbus still uses the old A=A B=B layout.

**Comment by jasarien** [comment]
This hasn't been an issue since Oct 3rd.

What version does Provenance say it is in settings? What process did you follow to update?

You should follow this process: https://github.com/jasarien/Provenance/wiki/Building-Provenance#updating-previous-checkouts

**Comment by gymnastboatman** [comment]
There needs to be a switch to change this back to A=A, B=B. Im not holding a SNES Controller! Im holding an Xbox style controller, and having the main button NOT be A is SO confusing! It makes it hard to play NES, SNES, GBC, and GBA games! 

If I was using a GBA shaped controller, my hand would naturally rest on A, which is in the B spot on an Xbox controller. But on an Xbox controller, my hand rests on where a GBA's B would be. Its not natural for this swap button mapping A=B. Until this is fixed, I have to use GBA4IOS. Because they got the most integral part of an emulator -controls - correct.

**Comment by jasarien** [comment]
No, you can wait until customisable button mappings are implemented. If that means you continue using gba4ios until then, then good for you.

**Comment by gymnastboatman** [comment]
Hopefully in your implementation includes the ability to change the button mapping for each individual controller. Because having to change it if I swapped controllers would be a little bit annoying.

**Comment by jasarien** [comment]
Would you like the moon on a stick, too?

**Comment by chriscthompson** [comment]
Is that in the next release?!? Just make sure the length and color of the stick can be adjusted or it'll be completely useless.

**Comment by gymnastboatman** [comment]
Not sure why the rude response, but alright. This is where I can request features, and I did. DIdn't know this is where I post what I want and have the creator be rude to my requests.

**Comment by jasarien** [comment]
Doesn't mean you can demand things, tell me how to build my project or make ultimatums. I didn't intend to be rude, it was a tongue in cheek comment in reply to your sense of entitlement. If you'd taken the time to read the existing issues you would have seen issue #56 where what you asked for is already outlined. 

I don't get paid by anyone to make Provenance, and in return I don't expect to be given ultimatums on what to implement or else you won't use my app. Enjoy GBA4iOS.

**Comment by whitverj** [comment]
Okay, so...to get this back on subject.

I just downloaded the current build from GitHub tonight, and built it for my Apple TV.  When playing NES games there, on my SteelSeries, the "X" key (which is where your hand naturally lies for the "B" key on an NES controller) is acting as "Start" and the "A" key is acting as...the "A" key, whereas its position is more inline with where the "B" key should be on a NES controller.

**Comment by jasarien** [comment]
That's by design. Start and select had to go some where. On a standard controller without triggers, the only buttons not in use on NES were the X and Y buttons. So I assigned them to start and select.

Once again, I'm not changing this and you can wait until the customisable controller mapping is implemented. 

I'm locking this conversation as I'm tired of discussing the same thing over and over.
