### ISSUE TITLE
Add Atari 2600 (Stella) Support

### ISSUE THREAD

**Issue by hstriepe** [jasarien/Provenance#187]
Had to ask for the "classic" first console. It would have to be ported from the Stella project.

**Comment by gingerbeardman** [comment]
It's based on https://github.com/OpenEmu/OpenEmu which does support Atari 2600, so it should be fairly easy to get this in.

**Comment by apexad** [comment]
So, are we to assume you are working on this then gingerbeardman? Since you say it's fairly easy.

**Comment by gingerbeardman** [comment]
@apexad never assume (no I'm not)

**Comment by wviana** [comment]
+1 👍🏻

**Comment by kudit** [comment]
@apexad :) LOL Makes sense

**Comment by k00k** [comment]
Yes, please :+1:

**Comment by JoeMatt** [comment]
I've compiled in Stella support in my fork & branch Stella

https://github.com/JoeMatt/Provenance/tree/stella

I can get the emulator to start and import a26 roms. I'm having issues with OpenGL though. Mostly due to my ignorance of OpenGL. 

One example is ```GL_UNSIGNED_INT_8_8_8_8_REV``` is not available in OpenGL ES. I also assume the endieness should be reversed for buffers for iOS as apposed to the OpenEMU code that I'm using as reference but I'm not exactly sure. 

I've used the Genesis core of Provenance as a template as well. If I use it's buffer type constants I can get some basic, but garbled, rendering until i push a button at which point there's a memory related crash probably due to invalid buffer sizes. Also audio never initializes. Not sure if this is due to sample rate issues or related to the OpenGL renderer issues. 

Maybe someone with more experience can take a look at it. I've spent a few hours so far and have published my progress as-is. Compiles, imports, but doesn't run a 2600 game.

Also the controller mappings are probably wrong but I didn't bother correcting it until a game runs to test.

**Comment by JoeMatt** [comment]
I've made some additional progress on my branch. The issues revolved around static linking libretro was conflicting with the statically linked libretro from Genesis. This probably isn't an issue with OpenEMU (it appears they use more than 1 copy of libretro as well) because they dynamically compile and load cores.

The games now run and render correctly. 
Outstanding issues,
gl crash after button press
No audio.

**Comment by beeblebox** [comment]
any luck @JoeMatt recently?

**Comment by JoeMatt** [comment]
I'm also working on the N64 port hoping to learn something since they're different approaches. Then I got busy with the 9 to 5 job. I'm going to revisit Stella this weekend. It should be pretty easy actually, I have a lot of core audio experience. I'll update as soon as I have something. Don't want to spam this thread.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Thu, Feb 25, 2016 at 5:30 PM -0800, "beeblebox" <notifications@github.com<mailto:notifications@github.com>> wrote:


any luck @JoeMatt<https://github.com/JoeMatt> recently?

-

**Comment by beeblebox** [comment]
@JoeMatt I feel stupid, I meant to ask this on the n64 thread, but either way thats great news. I think the n64 tvOS port is more wanted than stella. Good luck!

**Comment by JoeMatt** [comment]
Stella support is now working on my branch on Apple TV. It crashes on tablet/phone still though. Something to do with the on screen controls. It should work with a MFI controller.

**Comment by JoeMatt** [comment]
So this is pretty much ready to go. I'm up to date with master. Everything plays fine with Mi-Fi but for some reason on screen controls causes a crash on the next buffer draw. Maybe @jasarien  or someone familiar with that code could take a look?

**Comment by jasarien** [comment]
Implemented as part of #394
