### ISSUE TITLE
Hide Nav on tvOS when scrolling

### ISSUE THREAD

**Issue by typkrft** [jasarien/Provenance#196]
Since we can not touch these buttons at anytime on the top of the screen, they should disappear as you scroll down on the TVOS version. You could also just have it so if the user goes right or left of the row of games it selects the settings or the import roms button.

**Comment by ssstraub** [comment]
Oh how I would love a specific button press to select the Settings/Search/Import ROMs menu items without having to scroll through the entire list of ROMs every time!

**Comment by dashby07** [comment]
I think a better solution would to keep the buttons where they are, but make a "cover flow" interface for game cover art. That would allow us to have a large collection of games while avoiding endless scrolling.

**Comment by typkrft** [comment]
I think even better would be something like a short hold click on the touchpad to bring up a menu. To address the issue of search, because we all know how terrible text input is on the Apple TV currently, would be something like ![Example](http://i.imgur.com/b1it2Cn.png). The Playstation Store on the PS4 does this. I would also like to see recent games on the "top shelf" on the home screen, but I don't want to blow this project up with user interface enhancements since I'm not helping to work on it.

**Comment by mailman-zero** [comment]
I loaded in a lot on first run not realizing the interface wouldn't handle them well. I would love an easier way to get to Z from A.

**Comment by sevdestruct** [comment]
As for the discussion about library being unmanageablE this is getting taken care of by the 2.0 Nav and single core libraries (#714) and game library sorting (#721)  and then with later addition of rom collections (#715) which should resolve a lot of endless scroll. 

I'm sorry, but I can't see us or anyone doing a cover flow interface these days for anything practical,  cover flow was mostly a novelty interface and  wasn't much of a useful way to browse by cover art as it made scanning across large libraries visually (which all of our visual cortex' are programmed to do extremely well as humans: pattern recognition and all). We're aiming at more of a Plex-like nav with long press or edge swipe on remote..

----

Since this issue was originally about hiding the too bar nav for tvOS, that's pretty straight forward. So gonna rename this.. then check if it's even still an issue..

**Comment by sevdestruct** [comment]
…and after checking this is fixed in at least 1.4 release if not earlier, so closed.
