### ISSUE TITLE
[Feature Request] Auto Scan and Update ROMs Artwork (instead of changing individual custom artworks)

### ISSUE THREAD

**Issue by silvercomet** [jasarien/Provenance#207]
Lots of Roms when loading into Provenance do not show the artwork. I know that we do now have the option to choose custom artwork option when picking option for each Rom. However, I just don't like to have a bunch of rom artworks mixed together with my other work and friend photos. It just takes more time scrolling and harder to search for photos when you have unrelated items like that, especially if you have like 100 roms that do not have artworks with them, that would be 100 addtional photos.

I would like to see an added feature like of the UberNes system where you can simply name your Roms the same as the artwork then click the scan button that it will auto apply the correct artwork for the Roms. Of course the artwork folder then will be created within the Provenance Document directory like the BIOS for FDS. 

That would be so much faster and better and location-wise for the artworks which should be with the game roms, not other photos.

Just a thought on that. I hope you could implement this sometime in the future. Otherwise, great work James!

**Comment by jasarien** [comment]
If you use a good quality rom dump then you'll likely always get an artwork automatically added. It's the bad quality roms that don't match the database that don't get artwork. 

As for cluttering your photo library with artwork you don't have to save images to your photos in order to use them with provenance. You can simply copy the image from the web and paste it onto your rom to set the custom artwork. 

This achieves the same effect as you asked for without having to have a separate folder or autoscan with images named the same as roms. 

![paste](http://d.pr/i/1jQqI+)

**Comment by silvercomet** [comment]
Thank you so much James,

I did not know that, I will look for a better one or at least copy from web. However, just one more question, I use Battery Doctor to clean up the temp files sometimes so will the pasted artworks will get wiped out too? Last time I remember saving photos to library then picked artwork from there then deleted the photos and clean up the temp files and the artworks of roms were gone. I will try to see if that happens again but thank you for great support :+1:

**Comment by jasarien** [comment]
Deleting temporary files will remove any rom artwork, no matter how it was added. The artwork is copied into provenance and saved knots caches folder which gets empties when you delete tempory files. I'd recommend not doing this for provenance, or if you do, just be aware that you'll need to re add your custom artwork.

**Comment by silvercomet** [comment]
Thank you for clarifying it! Awating your support for other systems on Provenance
