### ISSUE TITLE
Possible to show how much storage provenance is using ? ATV4

### ISSUE THREAD

**Issue by appletv4** [jasarien/Provenance#216]
When you go to Apple TV /settings/general storage  
The app only shows 58mb or however big the app is but not the roms 
I know I have more than 5gb in there 

I imported the roms using the web browser 

With the Mame emulator it shows 2gb app size because I put the roms in the app before building 
Is that possible with provenance ?

Thanks

**Comment by jasarien** [comment]
Nope. 

Whatever is shown in Apple TV's settings is totally outside the control of Provenance or any app, for that matter.

The way Provenance is written doesn't support bundling ROMs with the app during build.

On Apple TV, local storage is not permanent - it is treated like a cache and isn't counted towards the app's storage usage, because it's purgeable. This does mean that ROMs and saves can be deleted at any time (but most likely in a low storage situation, with a Least Recently Used policy). It is recommended that you back your saves up regularly.

Issue #1 exists to eventually fix the local storage issue with tvOS, but it is still being discussed and a solution is not yet decided.

**Comment by appletv4** [comment]
Alright thanks , no biggie 
I got the 64gb anyway
