### ISSUE TITLE
16 new emulator cores introduced in OpenEMU 2.0...will these come to Provenance?

### ISSUE THREAD

**Issue by dashby07** [jasarien/Provenance#256]
The new update for OpenEMU has support for new emulation cores. Will these systems come to Provenance?

**Comment by RedLucas** [comment]
OpenEMU and Provenance are not close to feature parity, but use aspects of the code. I think the new emulator cores and the progress of OpenEMU is good news for Provenance, but at the end of the day each emulator core needs time to get working individually. I wish I had the skills like jasarien has to be able to advance this excellent project.

**Comment by appletv4** [comment]
@jasarien 
Do you think is a bad idea to install the app multiple times ,one for each system if you have a lot of roms 
And rename the apps "sega" "Nintendo" "gameboy" "Super Nintendo"

Currently I have to scroll thru game gear and GAMEBOY to get to Nintendo 
And the app takes 2 minutes to load in the beginning with 5gb of roms

**Comment by pmp174** [comment]
maybe you should try it . There isn't any real issue with that except updating would become more tedious since you would be installing an app multiple times. try to check if its set to release or debug in the scheme menu , that could be causing issues. Make sure you check that all the prefixes are different to sideload the app. I also suggest you open up an issue on app loading with high number of roms.

**Comment by appletv4** [comment]
@jasarien 
@RedLucas  would it be like starting over from scratch or adding new code into the current provenance?

**Comment by jasarien** [comment]
While Provenance's architecture is based on OpenEmu, it is not a direct port. Just because something has been implemented in OpenEmu doesn't mean it will be easy to implement in Provenance. Each emulator core has it's own individual issues that need considering when implementing that can influence the difficulty, effort required and time required to complete. Closing this issue as it's not specific. There are other issues for enhancement requests to add more cores, use those.
