### ISSUE TITLE
Soft menu on the left side

### ISSUE THREAD

**Issue by digitall-it** [jasarien/Provenance#264]
As many games use the 4:3 convention, there are lateral black bands that are left unused.

If you shift the game to the border, you can use the space for quick load/save, battery bar, time and social sharing.

![mockup](https://cloud.githubusercontent.com/assets/3578378/12096749/d2c8d47e-b317-11e5-84b9-a85bf700e98f.png)

**Comment by sevdestruct** [comment]
Absoribing this into #718 Overlay Overhaul. The specific suggestion is a bit of a conlict with both this ticket and #639 as planned for 2.0, and there is no plan to uncenter or otherwise left or right align the emulator view on screen, but quicker access ing a few key things in emulator view and some sort of mini expandable HUD is being looked into instead of more idle overlay clutter which addresses allmof this...so I'm going to close this ticket.
