### ISSUE TITLE
Not able to build for archive (IPA package) for tvOS

### ISSUE THREAD

**Issue by belltechdave** [jasarien/Provenance#270]
I can build the tvOS version in Xcode to the device successfully but when I try to build for archive to create an adhoc distribution IPA file I'm getting failures. One of the failures mentioned bitcode. I can provide further details if required. Thank you.

**Comment by pmp174** [comment]
Are you building it for a simulator or are you actually archiving?

**Comment by belltechdave** [comment]
I'm sure I was building it for a device and not for the simulator.

**Comment by T0XicGreif3r** [comment]
I have this problem as well, it is a linker error. Something to do with the Realm framework, I can't remember it exactly at the moment.

**Comment by nevyn** [comment]
The Realm framework is built without Bitcode support. This was a known issue for Realm for a few versions, since fixed: https://github.com/realm/realm-cocoa/issues/2585

Not sure how the bundled binary framework was built, but it needs to be redone with a newer version of Realm which ensures that bitcode is embedded in the framework.

**Comment by jasarien** [comment]
This should be fixed now, updated Realm to 0.98.1, which should include bitcode support.
