### ISSUE TITLE
Provenance Crashing Upon Opening

### ISSUE THREAD

**Issue by Joshysss** [jasarien/Provenance#282]
Hi,

I'm new so please be nice.  I have jailbroken my iPad 3 (aka the new iPad) with Pangu 1.1.0.  I am running iOS 7.1.1 and installed Provenance through the http://beta.unlimapps.com repository.  Everytime I open the emulator, it immediately crashes.  Is it because i'm still on 7.1.1? or is there another reason?

Thanks in advance

**Comment by jasarien** [comment]
iOS is not supported. You'll need iOS 8 or later

**Comment by ziggurism** [comment]
My Provenance is also crashing upon opening. It used to work fine, and I don't think I changed anything.

It's an iPhone5 running iOS 9.3.1. Provenance 1.2.6. Upon tapping the app, it shows the library screen for a very brief instant before crashing.

Here is what I saw in the xcode console while this crash happened:

Apr 20 16:28:42 tallbop3 syncdefaultsd[1291] <Notice>: (Note ) marked "com.me.keyvalueservice" topic as "enabled" on <APSConnection: 0x14d6eb00>
Apr 20 16:28:42 tallbop3 syslogd[830] <Notice>: ASL Sender Statistics
Apr 20 16:28:43 tallbop3 SpringBoard[856] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Apr 20 16:28:43 tallbop3 SpringBoard[856] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Apr 20 16:28:43 tallbop3 securityd[903] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Apr 20 16:28:43 tallbop3 securityd[903] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Apr 20 16:28:43 tallbop3 amfid[1294] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Apr 20 16:28:43 tallbop3 amfid[1294] <Error>: /private/var/containers/Bundle/Application/C6C47AD7-C1A4-42CF-BBFA-1DBB3B4D8B55/Provenance.app/Provenance not valid: 0xe8008015: A valid provisioning profile for this executable was not found.
Apr 20 16:28:43 tallbop3 com.apple.xpc.launchd[1] (UIKitApplication:org.athambia.Provenance[0xf1fe][1297]) <Notice>: Service exited due to signal: Killed: 9
Apr 20 16:28:43 tallbop3 assertiond[873] <Warning>: Unable to obtain a task name port right for pid 1297: (os/kern) failure (5)
Apr 20 16:28:43 tallbop3 SpringBoard[856] <Warning>: Unable to register for exec notifications: No such process
Apr 20 16:28:43 tallbop3 SpringBoard[856] <Warning>: Unable to obtain a task name port right for pid 1297: (os/kern) failure (5)
Apr 20 16:28:43 tallbop3 SpringBoard[856] <Warning>: Unable to obtain a task name port right for <FBApplicationProcess: 0x1a168680; org.athambia.Provenance; pid: 1297>
Apr 20 16:28:43 tallbop3 SpringBoard[856] <Warning>: Application 'UIKitApplication:org.athambia.Provenance[0xf1fe]' exited abnormally via signal.
Apr 20 16:28:43 tallbop3 SpringBoard[856] <Warning>: Application '(null)' exited for an unknown reason.
Apr 20 16:28:46 tallbop3 kernel[0] <Notice>: 121469.390721 wlan0.A[1952] updateLinkQualityMetrics@1991:Report LQM to User Land 50, fAverageRSSI -71

**Comment by jasarien** [comment]
The reason is staring you in the face - you just need to see it.

Hint:

> Provenance not valid: 0xe8008015: A valid provisioning profile for this executable was not found.

**Comment by jasarien** [comment]
The reason is staring you in the face -- you just need to see it.

Hint:

> Provenance not valid: 0xe8008015: A valid provisioning profile for this executable was not found.

(You need to renew the profile and rebuild.)

**Comment by ziggurism** [comment]
Thank you, sir. A fresh build fixed it. Do you know off-hand how long the expiration period is for these profiles?

Yeah, sorry I guess I didn't read through that log carefully enough.

**Comment by jasarien** [comment]
About 3 months I think.
