### ISSUE TITLE
Add ability to change cover art via web server's UI

### ISSUE THREAD

**Issue by drakkhen** [jasarien/Provenance#286]
It would be very convenient if the web server's UI showed current cover art which, when clicked, allowed users to upload alternative art.

This would also solve the repeated requests to change artwork on tvOS (#173, #188, #220, #225, #237, #284).  I realize that the tvOS interface is not an ideal (or even possible?) medium for feature.  Adding it to the web server could provide the missing tvOS functionality as well as an easier UI to work with on other devices.

Personally, I'd be okay with dropping this functionality from the iOS UI altogether and just having the feature on the web UI so there is only one way to do it, and one feature to maintain.

**Comment by Hanterdro** [comment]
+1

**Comment by stuartjmoore** [comment]
If anyone has any suggestions of where to start, this is something I’m going to try and implement.

**Comment by jasarien** [comment]
Not sure where you'd start - the main thing that needs to happen, though, is setting the property on the Realm-managed Game object for the artwork file url, which I'm not sure how you'd do via the web UI... 

It's not as simple as dumping the image into a folder somewhere and having the game find it automatically.

**Comment by lolkthxbai** [comment]
What about having a folder where you could upload custom artwork and then in the settings, assign the artwork to the correct game name?

**Comment by jasarien** [comment]
@davidmuzi was working on a way of adding artwork on tvOS using an image search UI.

**Comment by lolkthxbai** [comment]
Do you know if it searched for images online, a database of game covers or a local folder?

Also, how could I join the slack group?

**Comment by jasarien** [comment]
DM me your email on twitter (@jasarien)

**Comment by jasarien** [comment]
I don't know the specifics on the search. I think it might have just been something like a Google image search

**Comment by stuartjmoore** [comment]
@jasarien My going theory (still new to this codebase) was to mimic `moveCDROMToAppropriateSubfolder:` and import the images into the cache based on their filename.

**Comment by stuartjmoore** [comment]
@jasarien Finished (cleaning up for PR): https://github.com/jasarien/Provenance/compare/master...stuartjmoore:issue/286-web-ui-cover-art

It’s pretty basic. Name the image file the same as the rom file (`Super Mario Brothers 1.nes` → `Super Mario Brothers 1.nes.png`) and drag-and-drop into `/Cover Art`.

**Comment by lolkthxbai** [comment]
@stuartjmoore I've tested your changes for the the coverArtWatcher. It seems it might need some cleaning up; I was able to build the app successfully. I imported a ROM that is known to have no cover art (Pretty Soldier SailorMoon - Another Story). I imported the cover art jpg file, renamed it to the same name as the rom and placed it in the Cover Art folder. As soon as I did so, the app crashed and froze up. This is the error it gave me in Xcode:

`2016-12-23 22:13:19.068068 Provenance[8035:413098] *** Terminating app due to uncaught exception 'Invalid value', reason: 'Expected object of type string for property 'romPath' on object of type 'PVGame', but received: (null)'
*** First throw call stack:
(0x19073a51c 0x18fd2c55c 0x1021b6084 0x1021c8358 0x1021b9f30 0x1021b6850 0x1021b6148 0x1021aedac 0x1021a6010 0x1000443c4 0x10004e450 0x102b8d48c 0x102b8d44c 0x102b924b4 0x1906e7cf4 0x1906e58e0 0x1906139a8 0x1920bb198 0x1964ea110 0x1964e4fc4 0x10006c944 0x1901b1674)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

I quit the app (swiped up on the app in multitask view) and relaunched it. Sure enough, the new cover art was there on icon for the rom but Provenance crashed again after assigning Player 1 and 2 to my already connected controllers. Could you look into this?

**Comment by stuartjmoore** [comment]
@lolkthxbai What image filename did you use? I’ve used it fine for almost all my roms fine so far.

**Comment by lolkthxbai** [comment]
@stuartjmoore
😉 lol okay, so when you say zip them all together, you mean you want me to zip the jpg? Or zip the jpg + rom in a single archive?

**Comment by stuartjmoore** [comment]
Just the jpg(s). I opened a PR (with the crash fix), so feel free to discuss over there: https://github.com/jasarien/Provenance/pull/490

**Comment by davidmuzi** [comment]
You can see my approach here: https://github.com/davidmuzi/Provenance/tree/task/tvos-custom-artwork

My findings for missing artwork was that the md5 of the roms did not match anything in the openVGDB database, and the filename did not match anything exactly, either. But, if you do a search in the openVGDB you'd find there are several versions with slightly different filenames, and an artwork URL.

My approach just allows you to search the database and display the results with their artwork in the UI.  You then pick the entry that has the artwork you want, and then its URL is applied as the custom artwork.

If theres still interest I could spend some more time cleaning it up and open a PR

**Comment by lolkthxbai** [comment]
That sounds awesome 😎

**Comment by orenwolf** [comment]
@davidmuzi I think that's the best way to go about it. This approach allows us to use the same system the app uses anyway, just with some help on which art to change.

Please let us know if there's anything we can do to help test.

**Comment by sevdestruct** [comment]
@davidmuzi, looking to close out these old tickets. Over year old on this going cold, please submit a PR with your feature ( do consider the app has been converted to swift in the new dev branches ), in the meanwhile I'm closing this ticket. The current methods for getting custom artwork in app have worked pretty well and the cover art folder and roms folder have recently been merged into a single Imports folder with a single watcher in some of the dev branches, so bulk drops is easier all at once.. Pasting works well for most others..

Will reopen if necessary, but I foresee this as more of a Rematch/Fix Match interface in app in the future if it is to be revisited similar to how Plex works on the Server side web app to fix matches and choose altered cover art.
