### ISSUE TITLE
Provenance and Mame for tvOS suddenly stopped working. 

### ISSUE THREAD

**Issue by elbarbari** [jasarien/Provenance#292]
Nothing was changed. provenance just stopped working yesterday morning with an error provenance not available.

Also, Mame for tvOS stopped at the same time!!

Thank you.

**Comment by JerGitHub** [comment]
It's because you cert expired. Apple only gives out 3 month certs without a paid $99 dev account. 

I haven't figured out a way to extend a cert when building so every 3 months I have to build it and install again. 

Anyone know if you can change the cert expiration instead of having to rebuild every 3 months?

**Comment by jasarien** [comment]
There's no way to create a cert that lasts longer than 3 months without a paid account. You'll have to renew it every 3 months and rebuild.

**Comment by elbarbari** [comment]
Ok, great at leastI know why this happen all the sudden. But how do you renew a cert for another 3 months?

Do I have to renew it first, and then rebuild provenance? or Building will automatically renew the cert?

Thank you

**Comment by JerGitHub** [comment]
Figured that was the case without a paid dev account. Doesn't bother me since it forces me to update it to the latest release!

**Comment by JerGitHub** [comment]
Building will auto renew the cert for another 3 months

**Comment by jasarien** [comment]
You stated it working in #283. Closing.
