### ISSUE TITLE
Sega 32x

### ISSUE THREAD

**Issue by Gyurn** [jasarien/Provenance#296]
Hey, love the work you've done so far, I was wondering if you had any plans to add Sega 32x to future builds?

**Comment by pmp174** [comment]
The genesis core only supports normal genesis games and sega cd games. The 32x isn't supported and might never be supported. Another core would need to be added for it.

**Comment by jasarien** [comment]
As @pmp174 describes, Sega 32x emulation isn't provided by GenesisPlus GX (which provides Genesis, Master System and SegaCD), which means it would require a new core to support it and I don't currently have any plans to implement that right now.

**Comment by JoeMatt** [comment]
Reopen?

I have full speed (on ATV) working core on one of my branches.

https://github.com/JoeMatt/Provenance/tree/32x

Bugs yet to fix
- Sim builds broken, needs minor change to disable -DDRC_SH2 on non-arm platforms
- Core crashes on exit
- MFi buttons aren't mapped well
- Workspace needs to be tweaked. Need to build until you stop getting missing #import errors
- Touch screen controls I think aren't working, haven't tested since adding

All easy issues. I should be able to have this fixed when I get back from vacation mid September.
