### ISSUE TITLE
ROM Collections

### ISSUE THREAD

**Issue by jasarien** [jasarien/Provenance#3]
Split the games list into different lists by system, and allow custom lists for user-selected favourite games, etc

**Comment by apexad** [comment]
This generally seems fixed via #485.

**Comment by jasarien** [comment]
It implements one aspect of the feature, sure but I think collections would be more akin to like playlists, multiple user-created lists of roms. Like RPGs, or Platforms, etc.

**Comment by appletv4** [comment]
@apexad  more like tabs with different consoles that you can quickly switch to from anywhere by pressing menu on the Apple TV remote 
Something like that is what's needed 

Or maybe a hidden screen on the left side of the screen like plex ,with all the console names 


I wanna go from nes to snes without having to scroll Through  the entire library

**Comment by sevdestruct** [comment]
Been thinking about this as well, what do you guys think of it being an edge swipe side shelf view? Maybe combined with paginated views line apple springboard, so that the side shelf would function as shortcuts to pages but could still swipe to next set alternatively. Perhaps top tab and thus first convertible view could be recents still..

Assist from that wouldn't mind having a system sort order based on year or bit. Various sort  options would be great or manual sort via edit mode. 

Read mention of playlist collections. That would also be awesome

**Comment by appletv4** [comment]
I like like plex on Apple does it , on the left side on the screen if you swipe left again you get the hidden menu

https://www.flatpanelshd.com/pictures/newplexappletv-1l.jpg

**Comment by sevdestruct** [comment]
@appletv4 - right, actually I think Plex's side shelves in both iOS and aTV are both great for something we could utilize here for ROM collections.

**Comment by sevdestruct** [comment]
@jasarien Looking to close this and splice this up into 2 seperate pieces to implement potentially in phases, Core Nav/Core Libraries first (in 2.0), and [custom] Collections secondly in a 2.x release, as discussed with @JoeMatt
