### ISSUE TITLE
Configurable on-screen controls?

### ISSUE THREAD

**Issue by jkjwong** [jasarien/Provenance#306]
It states you can move position of controls but I can't see how to do this.  When playing Genesis in portrait mode on an iPhone the start button overlaps the A button.

How do I change positioning?

**Comment by jasarien** [comment]
Sorry for the confusion. This feature was removed when portrait orientation was added because it was causing a few issues. 

It might make it back in a future update.

**Comment by jmx773** [comment]
Well if adding this option back requires more time, I'd rather you resize them to a fixed position where they don't overlap.

Also increase the size of the touch locations of the L and R buttons, they're stupidly small and specific that there's even a small gap between the edge of the screen and the button itself, which is really annoying since I use my index finger for it and 80% of the time for some reason I keep hitting that gap.

Another thing is that the directional keypad keeps losing touch response whenever you move your finger out of it, EVEN when not lifting your finger off the screen. Most iPhone games make this stupid mistake and really ruins the experience, like the entire Metal Slug series.

Just sayin'.

**Comment by charlesvestal** [comment]
@jmx773 This comment comes off as incredibly rude, not to mention being out of band of this issue's scope.  If I may me revise this for you in a way that comes off as less rude to this author of free software, keeping in mind each of these should be a separate github issue:

"Understood. I'll open a separate issue about revising the Genesis layout. 

In addition, I have the following suggestions [which should each be separate issues]:

- the L and R touch targets currently don't extend to the edge of the screen and seem hard to hit in practice. Increasing the size would improve their reliability. 

- The directional keypad should retain focus while touch is down so that one can move their finger outside of its initial touch area while depressed and still maintain the d pad button press. 

Thanks tor the hard work on this project."

This is a free project done in someone's free time. Calling things stupid and barking orders of disparate issues makes it tough for an author to want to continue to maintain or at least, parse these comments. 

Just sayin'.

**Comment by jmx773** [comment]
@charlesvestal Yeah I guess I shouldn't have posted immediately just after I got frustrated, my bad.

**Comment by charlesvestal** [comment]
No sweat! Just want to make sure we can all be effective. Thanks for being considerate and taking constructive feedback.

**Comment by jasarien** [comment]
#56

**Comment by pitkevich80** [comment]
hmmmmm any way to change size for layouts buttons?  (For now too big sizes) 
Possible  buttons customized somehow?  (Something like Retroarch buttons size).

**Comment by jasarien** [comment]
This is already marked as a duplicate of #25 2 years ago why are you commenting here? 😂

**Comment by pitkevich80** [comment]
ooops sorry doesn't see it hehe
