### ISSUE TITLE
Aspect ratio option for 4" and up displays.

### ISSUE THREAD

**Issue by mithical** [jasarien/Provenance#33]
Users on 4" devices and up could definitely benefit from a "full screen" option in Settings. Natively not all games were made in a 16x9 aspect ratio, but many of us - me included - have grown used to a 'stretching' technique used in other emulators. I believe MAME4iOS uses this in-setting and GBA4iOS has this feature enabled depending if the skin includes the aspect ratio key.

**Comment by 1davi** [comment]
Can you add an option on portrait mode to show the game in the native resolution? For example the GBA screen resolution is 240x160, so on a retina screen that would be 480x320, you could center the image on the iPhone screen.

**Comment by GutlessGnat** [comment]
One of the main reasons I don't like to use provenance is the fact that you can't stretch the display to the iPhone 6+ display.

GBA4ios allows you to stretch the screen I can't imagine it would be too difficult to implement this into the settings.

**Comment by ramone12781** [comment]
Yes please add this option. He won't add it because 4:3 aspect ratio was the original aspect ratio for these old school games. But I wish he would just implement it. It can't be that hard to make this an option. The guy that made the .emu emulators had this in all his and it was great but you have to be jailbroken in order to get these emulators anymore.

**Comment by sevdestruct** [comment]
I'm closing this as work is being done on a less an more enhanced version of fullscreen, without just linear stretching it (Non-Linear Stretch: #639), which has another hybrid fullscreen idea that is being considered.
