### ISSUE TITLE
Blank White Screen on Apple TV 4

### ISSUE THREAD

**Issue by esbe02** [jasarien/Provenance#357]
Provenance doesn't open and gives me a blank white screen. I ended up deleting and re loading provenance thru xcode and it was working for about a week and now the same issue again. Anyone else experienced this before and know how to fix? I wonder what's causing the bug. Thanks in advance.

**Comment by appletv4** [comment]
Free Apple developer accounts now have a 7 day limit , app stops working after 7 days 

Your options are to 

 1-pay $100 for one year developer account to Apple 

2 - Pay $12 to a site like https://tv.ipwnstore.me/home.html , you pay then and they send you a link with instructions to download the app and you get to use the app for a year , much easier than doing it yourself with Xcode 

3-  you jailbreak the Apple TV 4 ,  install nitotv & download provenance , I don't know if this version has a year limit or 7 days or if is permanent 
But if a new Apple TV firmware update comes out that breaks the jalibreak I don't know if the app will continue to work 

4- keep reinstalling provenance every 7 days 

I went with option 2

**Comment by esbe02** [comment]
Ah... thanks for the tip. Option 2 sounds like the best option. Are there any other perks with other than Provenance for a year?

**Comment by appletv4** [comment]
Gives you kodi and other apps like that you can install , about 10 apps 
Popcorntime
Tvosbrowser 

Other than kodi & provenance I didn't see anything useful 
You can get Mame from them but it doesn't work because with Mame you import the roms during Xcode building 
And with the ipwnstore site you download the ipa app file from them and use ifunbox to drag & drop the app into  the atv4 , no Xcode involve
