### ISSUE TITLE
El Capitan 10.11.5, Xcode 7.3, losing my mind

### ISSUE THREAD

**Issue by drasson** [jasarien/Provenance#362]
Hi and thank you in advance for your development and support. I have followed the steps, thought i figured out where I went wrong, uninstalled Xcode and started from scratch about 4 times now. Each time I try to figure out what is going wrong but I can't figure it out. I keep on getting a successful build but ultimately I see that it fails. My latest issue is "Your maximum App ID limit has been reached. You may create up to 10 App IDs every 7 days" and now I can't even replicate my old issue. I have tried by doing the clone from the github site and also tried doing it the old fashioned way through the terminal. Nothing I try seems to work. I found plenty of issues that others have had that seem to fix the problem for them, but not for me. I am beginning to wonder if it has to do with the version of Xcode? Any help is greatly appreciated. Thanks

**Comment by drasson** [comment]
I'm embarrassed to say I have now invested about 6 hours of time trying to figure this out 👎

**Comment by jasarien** [comment]
Sounds like you're hitting the limitations of the free developer accounts. Every time you start from scratch, you're probably hitting the "fix it" button Xcode displays which creates a new app ID each time, and free dev accounts are limited to 10 per week - as you saw in the error message.

My advice would be to give it some time so that some of your App ID slots are freed up again (you might even need to login to the developer portal and delete them yourself). Once you have some free slots again, follow the guide as thoroughly as you can. If you want to ask for more help, you can add comments to this issue, but please be as detailed as you can. For example, writing something like "I keep getting a successful build, but ultimately I see that it fails" is a contradictory statement and creates confusion as opposed to helping me know what's going wrong. Consider writing things like why it failed, what specific error messages you see, what actually happens and what you expected to happen instead, etc.

**Comment by drasson** [comment]
Thank you for your reply. I was actually successful but now it is telling me "provenance isn't available" on my apple tv

**Comment by appletv4** [comment]
@drasson https://github.com/jasarien/Provenance/issues/357
