### ISSUE TITLE
Menu button crashes provenance

### ISSUE THREAD

**Issue by ashketchup2209** [jasarien/Provenance#378]
When I use the menu button provenance crashes and I have to restart my iPhone. It screwed up my network settings too at some point. Also, when I toggle the speed it only goes fast for a few seconds and it goes back to normal. 

I downloaded the app from ienchatify.net and did the date trick. I don't want to jailbreak my phone.

**Comment by jasarien** [comment]
I have no idea what ienchatify is - I don't provide support for any installation method other than downloading the code from this repository and compiling it to your own phone yourself (no jailbreak required, just a Mac and Xcode.)

It's likely you're using an old/modified version of the app, and since I have no idea where it came from or who compiled it or what modifications they may have made, I can't help with your issue.
