### ISSUE TITLE
How do you downgrade Provenance?

### ISSUE THREAD

**Issue by hatehope** [jasarien/Provenance#385]
I am actually very ashamed to ask since I dont have any programming knowledge at all but I have some issues downgrading Provenance 1.2.6 to 1.2.5. I´ve read the wiki but I still have a couple of questions:
What are the pre-requisites?
Is there a detailed guide?
Do you need a pc or can you do it directly from the phone?
Thanks for any answer, and sorry for me being such a moron lol

**Comment by james-rantmedia** [comment]
You will need a Mac (not a PC). It cannot be done directly from the phone.

You will need to checkout the source code using the 1.2.5 tag, like this:

```sh
git clone git@github.com:jasarien/Provenance.git
cd Provenance
git checkout 1.2.5
```

**Comment by jasarien** [comment]
You will need a Mac (not a PC). It cannot be done directly from the phone.

You will need to checkout the source code using the 1.2.5 tag, like this:

```sh
git clone git@github.com:jasarien/Provenance.git
cd Provenance
git checkout 1.2.5
```

Once you've done that you can then follow the instructions in https://github.com/jasarien/Provenance/wiki/Building-Provenance (ignoring the initial instructions since you've just done the above).
