### ISSUE TITLE
Provenance crashed when i pressed menu

### ISSUE THREAD

**Issue by omegaRJ** [jasarien/Provenance#477]
As the title says, the app crashed when i pressed menu on the middle top screen.
My device is iPad Pro on iOS 9.3.3

**Comment by jasarien** [comment]
Which version of Provenance? Did you download it from somewhere or build it yourself via Xcode?

**Comment by omegaRJ** [comment]
I got it from cydia repo

**Comment by jasarien** [comment]
Then it's likely a very old version that doesn't have the fix for the menu button crash as tracked here: #96 

I don't maintain any Cydia repos, so I don't recommend people install from them. 

The only way I support installing is building with Xcode. https://github.com/jasarien/Provenance/wiki/Building-Provenance
