### ISSUE TITLE
Roms disappearing.

### ISSUE THREAD

**Issue by Theiof** [jasarien/Provenance#518]
Hi! I absolutely love Provenance and the ability to relive the classics.

On AppleTV though the app keeps deleting the roms. Or maybe it resets/changes the destination path. No idea, but maybe they are still there but it just doesn't show them? Is that possible?

Either way, they keep disappearing. Re uploaded the roms yesterday and they are gone today again :( all saves gone too. It did work for like a couple of days. Now it seems to delete the roms every day or so. Tried rebuilding the app too.

Latest TVos and Provenance cloned a couple of days ago for the github rep through xcode 8. Using the same name & account every time in Xcode to sign. Anyone has a clue? Thanks!

**Comment by jasarien** [comment]
Is your apple TV low on space?

TvOS doesn't allow local storage for apps, with the exception of caching. Due to this limitation, provenance stores ROMs and saves in the caches directories. The caches directories may be cleared when the device is in a low storage space situation. 

Unfortunately there isn't anything Provenance can do to prevent this at this time. 

I would suggest freeing up some space on your device to see if this helps. 

The only other thing I can't think of is if you're rebuilding the app to your device using a different bundle ID. This will install as a separate version of the app on the device instead of overwriting the original app. In this case the roms and saves from the original app wouldn't transfer to the newly installed one.

**Comment by orenwolf** [comment]
Could provenance not add Roma to the project at build time, and use those to load the cache if it gets wiped?

Also, does that mean savegames are at risk of disappearing, too?

**Comment by jasarien** [comment]
> Could provenance not add Roma to the project at build time, and use those to load the cache if it gets wiped?

No because copyright laws prevent emulators from shipping with bundled ROMs. 

> Also, does that mean savegames are at risk of disappearing, too?

Yes, which is why you should always keep a backup. Backing up is good sense anyway.

**Comment by orenwolf** [comment]
Sorry, I was specific in my comment, but unclear on meaning. 

I didn't mean to imply that Roms be added on github. By "at build time", I meant they could be (optionally) added by the *user* as part of setting up the project to be built locally. The project would contain the skeleton infrastructure required to add them in, plus a note on the wiki that "Hey, a more permanent solution to using the web server to upload roms is to add them to the Xcode project - here's how". 

As for savegames, how are all my App Store games saving state? I guess exclusively in iCloud? I don't think there's a warning anywhere on the wiki or the readme that saves are ephemeral, or even more than a passing mention of backing up while describing file access methods.

**Comment by jasarien** [comment]
I guess the main issue with adding ROMs to the app and using them to reload the cache when it's wiped is that you'd end up in a loop. The cache gets wiped when the device is low on storage space. If the app just refills it when it's emptied (or if the user does it manually, it doesn't matter) then the system will just empty it again. It's an unavoidable 'feature' of the OS. 

Apps in the app store can benefit from using iCloud, and user it to store save information. 

As stated previously, since Provenance isn't in the app store, it can't use iCloud. 

Agreed that the wiki needs a section describing this behaviour.

**Comment by QuarterSwede** [comment]
Wasn't there talk of using DropBox or other cloud services to save roms/saves to? It would definitely solve this problem AND enable syncing between devices which doesn't exist currently.

**Comment by lolkthxbai** [comment]
@QuarterSwede what has worked for me has been to keep all my roms on Dropbox and using my iPhone or iPad to open the web server in safari so I can easily import my roms into Provenance since the web server page in mobile safari gives me the option to import from Dropbox. As for saves, I don't have a solution. I haven't backed up any of my save files. I imagine it would work the same way backwards though.
