### ISSUE TITLE
2x 8bitdo controllers, simultaneously.

### ISSUE THREAD

**Issue by Greedy1234** [jasarien/Provenance#523]
Now that bluetooth keyboard is supported on tvOS I went ahead and purchased 2 8bitdo NES30 Pros. I am so close to multiplayer retro gaming bliss thanks to Provenance, but since apple only allows one bluetooth "keyboard" to be connected at a time, this means single player is all we can do. Is there any potential work around for this?

Also - a more simple request. Can we get a mute game audio function? So we can listen to Apple Music while playing.

**Comment by Hanterdro** [comment]
Yeah, this would be great. But it's with the current implementation not easy.
See: https://github.com/jasarien/Provenance/pull/493#issuecomment-269618289

**Comment by sevdestruct** [comment]
Right now no, 8bitdo currently dropped iOS support and the only way they work is if you roll the drivers back to old firmware where they function as keyboard inout, pre-MFi hack. As such apple only allows one keyboard inout at a time. So currently no 8bitdo 2player. However, it may be possible to make 1 with a MFi controller but there is bugs with this at the moment because of how iCade inout conflicts with MFI, but might be resolveable - no promises.

As the request stands for 2x 8bitdo simultaneously.. No, Not unless 8bitdo bakes in MFi compliance in a firmware update or someone hacks together their own firmware (I wish), but there might be hope with @JoeMatt's side project to get controllers to input from an intercept, if you want to hold out for that. 

Unfortunately gonna cphave to close this..
