### ISSUE TITLE
Why SNES9x

### ISSUE THREAD

**Issue by davidbdeath** [jasarien/Provenance#576]
First off I am thankful for Provenance. Why SNES9x out of all of the SNES emulators this one never feels right. No matter what system i use it on, there is a lag or hesitation in the controls. How hard would it be to use a different core?

**Comment by cutecycle** [comment]
there's Zsnes, which is written in x86 assembly and highly inaccurate, and bsnes, which is so accurate it has a barely playable framerate on a sandy bridge i5.

**Comment by JoeMatt** [comment]
I suppose SNES could be build as part of Mednafen. The source is there we just don't compile it in. No one has ever complained about SNES9x before. We also don't have a mechanism at the moment for having more than 1 core per system so that would have to be added to allow user selection.

Interestingly, OpenEMU uses Mednafen for a lot of systems but not SNES, so maybe it's not so great. They only offer Higan (BSNES) and SNES9x.

**Comment by jasarien** [comment]
I would have used Higab instead of SNES9x when I first added SNES support, but it uses assembly for some parts and didn't have any ARM assembly implementation at the time.

**Comment by Cepheidsong** [comment]
I've been a fan of Nestopia for the much more enjoyable sound quality over fceux, but I figured there was probably a reason for all those picked, like easiest to implement (I heard fceux was best for debug for example)

SNES9x is probably best choice if you can't get Higan tho, I like it.
