### ISSUE TITLE
Feature Request - HTTP Server API

### ISSUE THREAD

**Issue by alec4** [jasarien/Provenance#578]
Hi there, 

is it possible to create a view http requests which would allow to download/upload roms/savestates/covers?
I want to write a little tool to syncronize the games and savestates of all my ios devices over http.
Great would be a site which lists all files with a download link and the creation and the modify date, so i could find out which file is the newest of all my ios devices.

Thank you and bye
Alec4

**Comment by jasarien** [comment]
I don't think this would work the way your would expect it to. If provenance didn't do anything clever when importing ROMs, then it might be a simple task, but that isn't the case. 

Provenance does a lot stuff when importing ROMs, like unzipping archives, figuring out which system a ROM belongs to, doing lookups from openVGDB to get artwork and titles, and storing all this meta data in a realm database. 

The upshot means that simply uploading files into folders won't provide you with a game library with artwork and stuff, because it won't have gone through the import process.
