### ISSUE TITLE
Nintendo Switch Pro controller

### ISSUE THREAD

**Issue by raphaelcosta** [jasarien/Provenance#591]
Is it possible to have support?

**Comment by jasarien** [comment]
No, iOS doesn’t have a fully open Bluetooth stack, and will only pair with certain types of devices. MFi controllers and iCade-based controllers (effectively just Bluetooth keyboards) are the only controllers that work with iOS.

**Comment by raphaelcosta** [comment]
@jasarien Also tvOS?

**Comment by jasarien** [comment]
Same applies to tvOS, yes.

**Comment by TimOliver** [comment]
Hi @jasarien! Awesome work on this library!

I have a Switch Pro Controller and a 4K Apple TV and I was wondering the same thing. I did some digging and it looks like people have managed to use the `BluetoothManager` private framework to detect non-BLE Bluetooth devices on iOS in the past. I'm considering trying to make a sample tvOS app to see if I can get my Apple TV to talk to my Switch Controller via the framework.

If you have absolutely zero plans to ever ship Provenance to the App Store (because private frameworks), is that a PR you would be interested in? :)

**Comment by JoeMatt** [comment]
There is a bit more bluetooth support in newer iOS's but you basically have to roll your own and I think it's limited to Bluetooth LE devices. It might be possible to create some kind of middleware helper hardware, like a battery packed small arduino that uses a custom bluetooth LE profile to translate commands between devices. Its something I'm toying with but probably a long ways out.
