### ISSUE TITLE
Audio crackling/stuttering with all (?) Game Boy Advanced titles 

### ISSUE THREAD

**Issue by pheraph** [jasarien/Provenance#61]
The iPhone 6 should be capable to play GBA titles with smooth sound, but the sound is stuttering.

**Comment by jasarien** [comment]
Are you certain you compiled in release mode? I noticed it is slow in debug, but was fine in release on my iPhone 6.

**Comment by jasarien** [comment]
I've just retested since I got home - if you built using the "Provenance" scheme (the debug scheme), then GBA emulation is choppy since there's no code optimisation applied in Debug mode. Can you clean-all (cmd+shift-K) and recompile using the "Provenance-Release" scheme? That should build in release mode with the code optimisations applied.

**Comment by jasarien** [comment]
The compression on the video is kinda heavy, but you get the impression of the performance: http://d.pr/v/17ldP

**Comment by pheraph** [comment]
Now I feel dumb. Building the correct scheme massively improved the performance. m)

Thanks!

**Comment by jasarien** [comment]
Good to know :)
