### ISSUE TITLE
iOS11 iPad Pro 12.9 PSX crash

### ISSUE THREAD

**Issue by emangamer** [jasarien/Provenance#630]
Loading PSX games just crashes. I have bios properly setup and am opening Dino crisis 2. I’m trying other games to no avail. iOS 11 broke?

**Comment by emangamer** [comment]
![855cbb4d-fc8d-4ef5-bcef-1037cd1d7706](https://user-images.githubusercontent.com/32711803/34324216-20252770-e838-11e7-9cdd-6543a667554b.png) Notably no games show up as recently played, so i think the emulator isn’t updated to 64bit. Try updating with some of the current ipad retroarch code for iOS

**Comment by jasarien** [comment]
This has nothing to do with 64 bit (the whole app is already complied as 64bit or else it wouldn’t even open on iOS 11 in the first place). 

I can see that there are plenty of entries in the recently played section in your screenshot (the second section, just below favourites) so I don’t know what you mean by that. 

Finally, it looks like your PSX ROMs are  it imported correctly. The ` Crisis 2 (USA) (Track...)` entry has ‘Genesis’ written on place of its missing artwork, meaning Provenance is incorrectly trying to import the .bin as. Genesis game. 

Common causes of this are the cue sheet and the binary image files not being named identically (except for the extension), or attempting to import the files individually rather than together in a zip. 

Check that the cue sheet is named exactly like the other binary images and that the content of the cue sheet has the correct file names in the track references.

**Comment by emangamer** [comment]
You were absolutely right. I used an app called iExplorer, fixed my files and now everything runs smoothly. I have a different issue now with the steel series nimbus controller but I’ll close this one and make a new one.

**Comment by anisozygoptera** [comment]
Hello. I am facing the similar issue and I did try the method above but still facing the problem. Did I miss something?

Many thanks!

![9bd0c8e5-0114-4782-a72e-bb6393ba594d](https://user-images.githubusercontent.com/37599681/37685280-e80d3172-2ccd-11e8-80ad-2335664fd4c6.png)
![e66ca781-9ca7-4474-934f-f5dfff32f81d](https://user-images.githubusercontent.com/37599681/37685282-e83e5d2e-2ccd-11e8-9cbe-1090911f578f.jpeg)

**Comment by anisozygoptera** [comment]
Thanks for your reply, @sevdestruct. I did read and follow the instruction there. I tried another ROM today but still remain the same - the app crashed and popped out. Then showed similar as above photo.

**Comment by JoeMatt** [comment]
@anisozygoptera The files should be zipped together when you upload. Delete any current entries first.

**Comment by JoeMatt** [comment]
Also what version are you using? We've made a lot of fixes in the develop branch but you have to build from source yourself.

**Comment by sevdestruct** [comment]
@anisozygoptera…

Joe is referring to the **[Requirements](https://github.com/jasarien/Provenance/wiki/Importing-ROMs#requirements-footnote)**, which are displayed at the very top of the [Importing ROMs](https://github.com/jasarien/Provenance/wiki/Importing-ROMs) wiki

<img width="614" alt="importing_roms_ _jasarien_provenance_wiki" src="https://user-images.githubusercontent.com/3118097/37805788-97034cd0-2df9-11e8-854e-4877f254f4a7.png">

And those requirements link to the to the bottom of that wiki for more details  with Instructions here: [multi-file ROMs](https://github.com/jasarien/Provenance/wiki/Importing-ROMs#multi-file-roms)

**Comment by anisozygoptera** [comment]
@JoeMatt & @sevdestruct, thanks for your reply and sorry of my delay. 
I did zip (I tried both .zip & .7z)everything to upload and the package was automatically unzipped on its own. I also tried to delete all the entries and reinstall but no use.

I am using iPad 9.7” (2017) with iOS 11.3.

Many thanks!
