### ISSUE TITLE
Feature Request: CRT Filter Toggle For Emulators

### ISSUE THREAD

**Issue by thekennygreene** [jasarien/Provenance#634]
Would really be awesome if there was a way of enabling or disabling the CRT Filter for selected Systems. Example: I love it with the SNES emulator, but it doesn't work with Playstation, so I constantly have to switch in on and off when I play them both.

**Comment by larssteenhoff** [comment]
and a scanlines only filter/ and strech game to fullscreen 16:9. ( with aspect ratio stretched to fill all screen)

**Comment by JoeMatt** [comment]
I'm looking into incorporating some other FOSS filters from other projects. Would probably be best to allow shaders to be toggled during gameplay from the pause menu instead of per core options.

Now, perhaps the system can remember which was the last shader used per core and re-use it on next load. Basically just saving to NSUserDefaults core id -> filter id.

**Comment by sevdestruct** [comment]
I'd like to second the request for stretch to 16:9, made by @larssteenhoff but I would highly recommend this be done as non-linear stretch so it maintains the integrity of the art on screen, centrally, maximizing the screen equity without making all the characters look fat/wide as linear stretch would do uniformly.

**Comment by larssteenhoff** [comment]
yes lets make it a request, ideally we could dice the stretch factor like some other enulatorors do laike retroarch.

as for the overlay, retro arcch supports just using a scanline image as an overlay, no shaders needed, thats also a good option

**Comment by sevdestruct** [comment]
Folding this into #680.
