### ISSUE TITLE
8bitdo Zero buttons

### ISSUE THREAD

**Issue by circa-one** [jasarien/Provenance#650]
The mappings for the A and B buttons on GBA should be flipped. They are technically right from a letter standpoint but the positions are opposite on the controller for what they were on GBA. It’s a picky thing, but it would be nice to have that. 

Also the buttons for PSX mappings for this controller are wrong. A should be X, B = Circle, X = Square, Y = Triangle. Start and Select are both just select and should be distinguished. 

Honestly it would be nice to be able to just manually select button mappings for specific platforms, similar to how OpenEmu does it.

**Comment by Davu67** [comment]
look the #582 I just posted a solution for your problem.

**Comment by sevdestruct** [comment]
Folding this into #699, also there is another PR for 8bitdo Zero by @leolobato in #713

**Comment by circa-one** [comment]
@Davu67 how did you get it to recognize the controller? I plugged mine into my PC and it says "No controller"

**Comment by sevdestruct** [comment]
@circa-one: PC? This GitHub project is an iOS/tvOS app…unless you are talking about trying to use with the Xcode simulators, or just trying to sort out reading the controller output and trying to help solve this…If not, and you're just looking for support for another project, I suggest you reach out to the user specifically instead of commenting on [closed issues](https://github.com/jasarien/Provenance/wiki/Issues-Usage) (heads up, we are working on getting a more accessible community platform via Discord or something similar going to help our users connect and discuss openly and in direct messages without cluttering the much more focused use of our Issues board. There is currently an open vote for this and others in #733, if you want to cast a vote there). 

That said…Sorry to be a stickler, but…

⚠️ **[This thread _is closed._](https://github.com/jasarien/Provenance/wiki/Issues-Usage)** Please follow where the links posted in the comments above take you before posting and either comment on the two pending 8bitdo Zero PRs (#582, #713), that are proposed to solve support for this particular controller -- or for more information about known issues and continued support for iCade controllers in general (but, especially 8bitdo series), please follow the conversation in the iCade Rehaul thread (#741).

**Comment by jasarien** [comment]
@sev he was talking about @davu67’s solution for remapping the iCade buttons using a firmware mod.

**Comment by sevdestruct** [comment]
thanks, will edit my reply, but this is still closed, the PR is a perfect place for that convo or in the rehaul thread
