### ISSUE TITLE
iOS ripoff app spotted?

### ISSUE THREAD

**Issue by clobber** [jasarien/Provenance#66]
Can you hop on IRC when you get a chance? Want to discuss https://itunes.apple.com/app/id982939500

**Comment by pheraph** [comment]
See also https://twitter.com/pheraph/status/590930707637231616

**Comment by clobber** [comment]
The app should be simple enough to take down via: http://www.apple.com/legal/internet-services/itunes/appstorenotices/

The seller has demonstrated he hasn't read or understands any of the licenses involved. There are several issues, all of which you can claim in a takedown:

* The seller is bundling emulators licensed for non-commercial use: SNES9x and Genesis Plus GX.
* The seller is bundling homebrew games licensed for non-commercial: e.g. https://github.com/OpenEmu/OpenEmu-Update/blob/master/Homebrew/NES/Driar/Driar.txt
* The seller is bundling emulators licensed under GPL and has released no source code: e.g. Nestopia
* The seller is not including required license acknowledgements: e.g. Provenance and OpenEmu licenses https://github.com/jasarien/Provenance

...and worst yet, the seller has designed this app with a backdoor to load commercial software: http://toucharcade.com/2015/04/21/homebrew-indie-games-is-a-secret-emulator-on-the-app-store-but-its-useless-if-youre-on-ios-8-3/

His app is an emulator bundle masquerading as "homebrew" games. This has happened too many times to list (think "app X sneaks secret emulator into app store!" stories) but another famous case is Gridlee http://toucharcade.com/2013/01/26/mame-is-back-in-the-app-store-for-now-with-gridlee/ 

Seller contact details: Jorge Moreno jorgemoag@gmail.com

@jasarien, don't let this guy get away with it. I'm surprised the app has been up on the store this long already.

**Comment by jasarien** [comment]
I've submitted a DMCA takedown complaint. I included all the details clobber mentioned except the 'backdoor'. I didn't know he'd left that in for versions prior to 8.3.

I'll add it as extra info. And I'll update this issue as it progresses.

**Comment by jasarien** [comment]
I sent this reply to Apple's Legal team when they responded to the initial complaint telling me "only rights holders can submit claims":


Hi Justin,

I, James Addyman, am the legal rights holder for the Provenance project - http://github.com/jasarien/provenance - Notice in the license text for Provenance:

Provenance License (Simplified BSD)

Copyright 2015 James Addyman (JamSoft). All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

	• Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
	• Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY JAMES ADDYMAN (JAMSOFT) "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL JAMES ADDYMAN (JAMSOFT) OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of James Addyman (JamSoft).

The claim I submitted is in regard to the app “Homebrew Indie Games” (Apple ID: 982939500) that has used code from the Provenance project which is licensed under the above terms. “Homebrew Indie Games” does not conform to the license terms, notably by not providing attribution.

The app in question is violating the terms of several other licenses including, but not limited to GPL and Creative Commons Non-Commercial. I will forward this response to the other rights holders so that they may make their claims too.

Finally, it has also come to light that “Homebrew Indie Games” also violates the App Store Guidelines, by providing a hidden method to load and execute unsigned/unreviewed binary code in the form of ROM images of copyrighted console cartridge games. The specific clauses follow:

• 2.4
	Apps that include undocumented or hidden features inconsistent with the description of the App will be rejected

• 2.8
	Apps that install or launch other executable code will be rejected

I await your response,
James Addyman

**Comment by clobber** [comment]
Yeah that is nonsensical of them; you are the rights holder. Both to your front end and the forks of the code (emulators) you contributed to which the seller is now using.

**Comment by asos-jamesaddyman** [comment]
Looks like Homebrew Indie Games is no longer available on the App Store. I haven't heard anything back from Apple after my reply, so I don't know if it was Apple's action or if the dev simply took it down himself. I'll keep this thread updated.

**Comment by asos-jamesaddyman** [comment]
I received confirmation from Apple that the DMCA claim had been issued to the developer of Homebrew Indie Games. The developer emailed me directly (copying in Apple Legal as well), to tell me the app had been removed several hours before Apple issued the claim.

I don't know how true that is, or what the real sequence of events were, but it appears the end result is the same.

**Comment by jasarien** [comment]
One of these days I'll remember to post on the correct account... Anyway:

Looks like Homebrew Indie Games is no longer available on the App Store. I haven't heard anything back from Apple after my reply, so I don't know if it was Apple's action or if the dev simply took it down himself. I'll keep this thread updated.

I received confirmation from Apple that the DMCA claim had been issued to the developer of Homebrew Indie Games. The developer emailed me directly (copying in Apple Legal as well), to tell me the app had been removed several hours before Apple issued the claim.

I don't know how true that is, or what the real sequence of events were, but it appears the end result is the same.

**Comment by clobber** [comment]
That's great news and thanks for following up on this. So I had heard the seller said "I do not need an application whose components can be controversial so I will remove the application from the sale" after numerous emails with the RetroArch folks, so who knows whether it was voluntary or a result of the DMCA claim. Either way, glad it's gone!
