### ISSUE TITLE
PSX dualshock not working (8bitdo)

### ISSUE THREAD

**Issue by CrimsonShadow11** [jasarien/Provenance#699]
I run the emulator using the 8bitdo Nes30Pro controller which has Dinput and for some reason the game doesn’t automatically pick this controller up as dualshock input, any idea what the issue is ?

**Comment by sevdestruct** [comment]
I have some 8bitdos and I'm gonna say this is a firmware issue. The old firmware hacks it in as virtual keyboard, predating MFI compliance, which could be related to this. They also dropped support for iOS on those controllers in latest firmware. I have the SFC30Pro and I have to roll mine back if I want to use them on tvOS. Can you specify what you mean by PSX dualshock not working on your NES30Pro? iCade input is problematic and not perfectly supported, 1. And 2, some games required the analog switch to joystick input in case that, so what game? I don't think Analog simulation is not currently implemented for that to work automatically.

Otherwise recommend getting a Steelseries Nimbus or another MFi controller that is well supported or wait for what Joe is currently working on to get a real PS controller working with the app.

**Comment by CrimsonShadow11** [comment]
when I say that dualshock doesn’t work is because the emulator doesn’t pick up the controller as having dualshock input, it just reverts to the original psx controller without the two jousticks and second shoulder buttons even though the nes30pro has the basic dualshock setup and for some reason the start and select buttons aren’t mapped to the start and select buttons on the controller so I got to press start on the pause drop down bar, so it could be the controller’s firmware, I am wanting to buy a cheap android tablet souly to set it up as a switch alternative anyway but I don’t know if provenance is on android

**Comment by jasarien** [comment]
> but I don’t know if provenance is on android

It is not and never will be.

**Comment by CrimsonShadow11** [comment]
fair enough, there’s probably duzons of emulators on android anyway

**Comment by jasarien** [comment]
N64 is in the develop branch.

**Comment by CrimsonShadow11** [comment]
oh nice, N64 is my favourite system with xbox coming in a close second, I will be awesome to play some goldeneye multiplayer on the go (definantly not playing as oddjob XD)

**Comment by sevdestruct** [comment]
Please keep the thread on topic, N64 is already in dev - we get notifications for posts so this isn't an freeform discussion board, sorry.

----

There's been a ton 8bitdo Issue threads already, maybe we can repurpose this for all iCade 8bitdo bugs in one, or fold into one new one with all the bugs in a list (no promises with iCade support, it's pretty hacky to begin with for 8bitdo)

**Comment by CrimsonShadow11** [comment]
this is a good iea actually, seeing that 8bitdo controllers are pretty popular there is bound to be problems

**Comment by sevdestruct** [comment]
on second thought, closing this in favor of new ticket, instead of hijacking it's purpose -- cleaner...
bumping this to #741
