### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Chursh** [jasarien/Provenance#732]
Any idea when a new release update will come out? 1.4 is kinda outdated with PSX having the aspect ratio misaligned, would help the windows users that can't xcode alot!

**Comment by gh0sti** [comment]
It is being worked on, it will take awhile. Please be patient.

**Comment by Chursh** [comment]
No problem! Cheers for the quick response bud!

**Comment by sevdestruct** [comment]
@chursh, PSX alignment has already been fixed in dev branch..
----
There are milestones now so everyone can defer to those from now on for release as schedule.
----
This is for issue posts. Not a discussion bosrd, guys. We are looking into a better means for general questions and community engagement. 

I guess I could make this issue have a better or more useful purpose and look for votes on a platform..or I'll just do that in a new ticket (I know, but…) so we can do one focused discussion on where general public discussions should go and then link to it from the GitHub from now on.
