### ISSUE TITLE
"Super Mario All-Stars + Super Mario World" not able to get box art

### ISSUE THREAD

**Issue by cplr** [jasarien/Provenance#88]
I think there is an issue in the query for art when there is a + in the title (that's my hunch anyway). In the game database used, there is an entry for "Super Mario All-Stars + Super Mario World", but even with a matching md5 hash for the rom, it does not properly load the box art.

**Comment by jasarien** [comment]
If the md5 hash matches then the title search isn't executed so, that's strange. Also a direct md5 match should only return one result. I'll look into it.

**Comment by jasarien** [comment]
I had a look and it seems to be a simple case that there is no box-art for that particular release in the database, and there hasn't been any updates to OpenVGDB since I included it in Provenance, I'm afraid. 
http://d.pr/i/13P51

The only solution is to add your own custom artwork by tapping and holding on the game and choosing "Choose Custom Artwork" from the menu.

**Comment by cplr** [comment]
Ha! I looked close enough to find the matching md5 but didn't look to see if it actually had artwork. Thanks for checking :).
