### ISSUE TITLE
Add support for NES, Gameboy, Gameboy Advance, and other rom formats.

### ISSUE THREAD

**Issue by XeresRazor** [jasarien/Provenance#92]
Only SNES and Genesis rom types have UTI entries at the moment, preventing other rom types from being opened in Provenance.
In particular, this is preventing these rom types from being opened from the new iCloud Drive application in iOS 9.

I've started a branch to fix this and will submit a pull request shortly.

**Comment by jasarien** [comment]
hm, I think the UTI settings might be a hang over from an early version... For a long while Provenance has only dealt with zip archives when opening externally. If you add the other UTIs, Provenance will open the files, but they likely won't be imported, since the importer only looks for and imports zips after extracting them.

**Comment by XeresRazor** [comment]
We might want to take a look at reimplementing import of unzipped rims then. With the iCloud Drive app, it can be useful to store uncompressed rooms there for OpenEmu and share them with Provenance.

**Comment by jasarien** [comment]
Closing this issue, as it's superseded by #83
