### ISSUE TITLE
siri remote as controller?

### ISSUE THREAD

**Issue by salino2835** [jasarien/Provenance#98]
i got it installed on the new apple tv through Xcode 7.1 beta and selected tvOS instead of master. Was i still supposed to select master or was i right in selecting tvOS since i installed it on the apple tv? I downloaded a pokemon game and it loaded but when i try to play with the siri remote i can only go up and down can not go left or right. Did i forget to do something in Xcode?

**Comment by jasarien** [comment]
You should select the 'Master' branch from now on, since the tvOS features has been merged into 'Master'.

When you open the project in Xcode, at the top near the Play/Stop buttons is a button that allows you to select a Scheme and a device. You should select "ProvenanceTV-Release" for the scheme and "AppleTV" for the device.

Unfortunately the Siri Remote is too limited to play nearly all emulated games that Provenance supports because the systems require more buttons than the remote provides access to. For example, the GameBoy has a Direction Pad, Start, Select, A and B buttons. Thats 4 buttons in addition to the direction pad, and the Siri Remote only exposes 2 usable buttons (one is clicking the touchpad, and the other is the play/pause button) and the touch pad for movement.

As for only being able to move up and down and not left or right, I think this is a bug related to handling the Siri Remote input, which I am working on refactoring over this weekend.

However, I would strongly recommend picking up one of the wireless MFi Game Controllers, such as the Steelseries or MOGA game controllers if you want the best experience from Provenance or any other games that may be released in the future. The Siri Remote just isn't good enough as a controller, despite what Apple says.

**Comment by salino2835** [comment]
thank you so much for your very quick replay! i will re-upload it and definitely look into buying a game controller. Keep up the good work!!
