### ISSUE TITLE
Games cut off (iPad Air 2 iOS 9 GM)

### ISSUE THREAD

**Issue by Shawzborne** [jasarien/Provenance#99]
Game is cut off on left side possibly right side as well

Advance wars gba. 

![](http://i.imgur.com/jdDsMFx.jpg)

**Comment by jasarien** [comment]
Aw man, that sucks... thought I had the aspect ratio stuff fixed...

**Comment by jasarien** [comment]
Should be pretty easy to fix... the GBA has a screen resolution of 240 x 160 or 3:2 aspect ratio. When the screen is scaled ti fit the iPad's height in landscape (768 points), the width is scaled at the same ratio, making it 1152 points, which is just a little bit bigger than it's landscape width which is 1024. Just need to add a restriction so that the view never exceeds the width/height of the screen it's on. Thanks for reporting.

**Comment by Shawzborne** [comment]
I'm trying to help best I can sorry, it only means the app will be even better

**Comment by jasarien** [comment]
No worries man, it's good! :P

**Comment by jasarien** [comment]
Should be fixed in 843e443236f6584ead1c01930d3427cea16e976f
Here's a screenshot to compare with the one posted in the original report: 
![image](https://cloud.githubusercontent.com/assets/104444/10119489/39a04754-648f-11e5-8457-5f1012274b6a.png)
